# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  major: 1
  minor: 0
  brpatch: $[counter(variables['build.sourcebranchname'], 0)]

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/deploy.zip'
    replaceExistingArchive: true
    
# - task: PublishBuildArtifacts@1 $(major).$(minor).$(brpatch)
#   inputs:
#     artifactName: artifact1
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#   displayName: 'Publish npm artifact'

#- task: PublishBuildArtifacts@1
#    displayName: 'Publish Artifact'
#    inputs:
#      PathtoPublish: '$(build.artifactstagingdirectory)/CloudDemo.Mvc.zip'
#      ArtifactName: '$(ArtifactName)'