trigger:
- main

variables:
  major: 1
  minor: 0
  brpatch: $[counter(variables['major.minor'], 0)]

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
# - task: CopyFiles@2
#   inputs:
#     sourceFolder: '$(Build.SourcesDirectory)'
#     contents: |
#       src/*
#     targetFolder: '$(Build.ArtifactStagingDirectory)'
#   displayName: 'Copy project files'

- task: ArchiveFiles@2
  inputs:
   rootFolderOrFile: '$(Build.SourcesDirectory)/src'
   includeRootFolder: true
   archiveType: 'zip'
   archiveFile: '$(Build.ArtifactStagingDirectory)/test.zip'
   replaceExistingArchive: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     artifactName: newartifact
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)/tar'
#   displayName: 'Publish npm artifact'
- task: UniversalPackages@0
  displayName: Publish a Universal Package
  inputs:
    command: publish
    vstsFeedPublish: 'artifact-crete/test-artifact'
    vstsFeedPackagePublish: 'new'
    versionOption: custom
    versionPublish: '$(major).$(minor).$(brpatch)'
    publishDirectory: '$(Build.ArtifactStagingDirectory)/'
