# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  major: 1
  minor: 0
  brpatch: $[counter(variables['major.minor'], 0)]

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'
# - task: ArchiveFiles@2
#   inputs:
#    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
#    includeRootFolder: false
#    archiveType: 'zip'
#    archiveFile: '$(Build.ArtifactStagingDirectory)/deploy.zip'
#    replaceExistingArchive: true

#- task: PublishBuildArtifacts@1
#  inputs:
#     artifactName: artifact$(major).$(minor).$(brpatch)
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#  displayName: 'Publish npm artifact'
- task: UniversalPackages@0
  displayName: Publish a Universal Package
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'artifact-crete/test-artifact'
    vstsFeedPackagePublish: 'artifact1'
    versionOption: custom
    versionPublish: '$(major).$(minor).$(brpatch)'
